# Generated by Django 4.2.7 on 2025-08-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('monte_carlo', 'Monte Carlo'), ('bootstrap', 'Bootstrap')], max_length=20)),
                ('n_samples', models.IntegerField()),
                ('alpha', models.FloatField(default=0.95)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('lending_file', models.FileField(upload_to='lending_files/')),
                ('recovery_file', models.FileField(upload_to='recovery_files/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provision_value', models.FloatField()),
                ('cumulative_balance', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simulations.simulation')),
            ],
        ),
    ]
