# Generated by Django 5.0.2 on 2025-08-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='n_samples',
            new_name='num_samples',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='name',
        ),
        migrations.AddField(
            model_name='simulation',
            name='confidence_interval',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='percentiles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='real_provision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='simulated_provisions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='lending_file',
            field=models.FileField(upload_to='uploads/lending/'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='method',
            field=models.CharField(choices=[('montecarlo', 'Monte Carlo'), ('bootstrap', 'Bootstrap')], max_length=20),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='recovery_file',
            field=models.FileField(upload_to='uploads/recovery/'),
        ),
        migrations.DeleteModel(
            name='SimulationResult',
        ),
    ]
