# Generated by Django 5.0.2 on 2025-08-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_rename_n_samples_simulation_num_samples_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='lending_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='recovery_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='lending_file',
            field=models.FileField(upload_to='csv_files/lending/'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='recovery_file',
            field=models.FileField(upload_to='csv_files/recovery/'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
    ]
