# Generated by Django 5.0.2 on 2025-09-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0004_simulation_lending_data_simulation_recovery_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='real_cumulative',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='lending_file',
            field=models.FileField(upload_to='simulations/lending/'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='method',
            field=models.CharField(choices=[('montecarlo', 'Monte Carlo'), ('bootstrap', 'Bootstrap')], default='montecarlo', max_length=20),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='num_samples',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='recovery_file',
            field=models.FileField(upload_to='simulations/recovery/'),
        ),
    ]
